// The Valtz mark as geometry: its ribbon layers, traced from the painted
// original (the 1024 px artwork; y down), each a band between two edge
// curves.
//
// Why traced 2.5D layers and not a 3D ribbon: the artwork is a ribbon
// wrapped helically down a narrowing cone, folded at the base and
// doubled back behind the film strip -- several sheets whose visible
// edges ARE the design. Modelling that in 3D and hoping the projection
// lands on those edges did not get close; tracing the edges and
// shading each sheet as the surface it is does. Every layer is a
// triangle strip between its two edges (straight chords), drawn back to
// front, with colour baked per vertex from a small (t along, v across)
// table sampled from the artwork, and luminous rims and a metallic
// sheen added in the shader. The edges themselves are MEASURED from the
// artwork (MarkTrace.swift, generated by tools/valtz-icon/trace-mark).

import Metal
import simd

enum MarkGeometry {
    /// A layer: edge A and edge B, both running the same way along the
    /// sheet (t = 0 -> 1); v = 0 at A, 1 at B.
    struct Layer {
        var a: [SIMD2<Float>]
        var b: [SIMD2<Float>]
        /// sRGB 0-255 colours at t stops (rows) x v stops (columns, evenly
        /// spaced from edge A to edge B).
        var t: [Float]
        var colors: [[SIMD3<Float>]]
        var rimA: Float
        var rimB: Float
        var film = false           // cut the perforations out of it
        /// The sheet's cross-section, for the metallic sheen: how far it
        /// curves across its width (radians) and where it faces the
        /// viewer most squarely (v).
        var curve: Float = 1.3
        var facing: Float = 0.5
        /// Round the sheet's end off over this fraction of its length,
        /// instead of letting its two edges meet in a corner.
        var capEnd: Float = 0
        /// How far (design px) the glow of edge A / B reaches into the
        /// sheet, along its length: the artwork's edges are not lines but
        /// a hairline falling off through yellow and orange into the
        /// sheet's own colour -- broad round the U, narrow on the strip.
        var glowA: (Float) -> Float = { _ in 6 }
        var glowB: (Float) -> Float = { _ in 4 }
        /// The glow's warmth along edge A: 0 = yellow into orange (most
        /// edges), 1 = pink into red (the curl's underside).
        var glowHueA: (Float) -> Float = { _ in 0 }
    }

    /// The painted artwork's extent (design px), and so its centre.
    static let bounds = (min: SIMD2<Float>(50, 130), max: SIMD2<Float>(995, 868))

    // ---- edges (measured: MarkTrace.swift) --------------------------------

    static let leftSilhouette = MarkTrace.leftSilhouette
    static let lipTop = MarkTrace.lipTop
    static let lipInner = MarkTrace.lipInner
    static let diagonal = MarkTrace.diagonal
    static let foldRight = MarkTrace.foldRight
    static let sCurve = MarkTrace.sCurve
    /// The strip starts where the S-curve's tail meets the bottom outline,
    /// so it fills the sliver under that tail, as in the artwork. Its left
    /// edge runs up the tail and on up the S-curve -- one smooth curve
    /// through the fold's tip -- hidden under the fold, across to the
    /// crotch, and up its outer edge and over the crest.
    static let stripLeft: [SIMD2<Float>] =
        MarkTrace.sCurveTail.reversed()
        + MarkTrace.sCurve.reversed().dropFirst().prefix { $0.y > 758 }
        + [[468, 700], [460, 660]] + MarkTrace.stripOuter
    /// Its right edge: along the bottom outline to the base, up the
    /// outline, then against its curled end.
    static let stripRight: [SIMD2<Float>] =
        MarkTrace.bottomRun + MarkTrace.stripLowerRight.reversed().dropFirst()
        + MarkTrace.stripEdge.dropFirst()
    static let tailOuter: [SIMD2<Float>] = MarkTrace.tailOuter.reversed()
    static let holes = MarkTrace.holes
    static let holeShapes = MarkTrace.holeShapes
    static let holeRadius: Float = 4.5

    // ---- the layers, back to front ----------------------------------------

    static var layers: [Layer] {
        // The inside is bounded by the front sheet's long edge down to the
        // fold's tip, then by the S-curve's tail into the bottom outline.
        let longEdge = lipInner + diagonal.dropFirst() + foldRight.dropFirst()
            + MarkTrace.sCurveTail.dropFirst()
        let front = lipInner + diagonal.dropFirst()
        func c(_ r: Float, _ g: Float, _ b: Float) -> SIMD3<Float> { [r, g, b] }
        // Colours sampled from the painted artwork (sRGB).
        return [
            // The strip's end, behind it: orange and gold low down,
            // coral-red in the curl.
            Layer(a: MarkTrace.stripEdge, b: tailOuter,
                  t: [0, 0.4, 0.7, 0.85, 1],
                  colors: [[c(240, 120, 50), c(252, 165, 70), c(253, 192, 88)],
                           [c(230, 100, 45), c(252, 134, 51), c(252, 150, 55)],
                           [c(200, 70, 60), c(221, 95, 80), c(240, 125, 75)],
                           [c(140, 20, 35), c(170, 45, 55), c(215, 90, 75)],
                           [c(165, 42, 50), c(200, 80, 70), c(235, 125, 80)]],
                  rimA: 0.35, rimB: 1.3, curve: 1.6, facing: 0.35,
                  glowA: { _ in 3 }, glowB: { _ in 16 }),
            // The film strip: brown-orange in the shade of its left edge,
            // cream along the perforations and its right edge.
            Layer(a: stripLeft, b: stripRight,
                  // From the base it is the strip's red underside turning,
                  // then orange, gold and cream up to the crest.
                  t: [0, 0.1, 0.22, 0.34, 0.5, 0.8, 1],
                  colors: [[c(200, 45, 45), c(165, 21, 39), c(175, 30, 42),
                            c(215, 70, 55), c(240, 120, 70)],
                           [c(225, 90, 70), c(185, 40, 45), c(252, 80, 72),
                            c(240, 105, 80), c(230, 110, 80)],
                           [c(236, 120, 60), c(221, 115, 86), c(245, 160, 100),
                            c(230, 130, 90), c(221, 115, 86)],
                           [c(240, 140, 60), c(225, 140, 88), c(248, 185, 111),
                            c(228, 128, 90), c(221, 115, 86)],
                           [c(215, 125, 60), c(165, 110, 78), c(210, 165, 110),
                            c(252, 220, 142), c(251, 226, 193)],
                           [c(241, 125, 40), c(241, 140, 55), c(250, 200, 130),
                            c(253, 232, 180), c(252, 225, 180)],
                           [c(253, 186, 87), c(253, 195, 110), c(253, 210, 140),
                            c(250, 190, 120), c(236, 140, 80)]],
                  rimA: 1.5, rimB: 1.1, film: true, curve: 1.2, facing: 0.7,
                  glowA: { _ in 11 }, glowB: { t in t < 0.25 ? 12 : 5 }),
            // The inside: the deep magenta underside of the curl, under
            // the lip and below the S-curve.
            Layer(a: MarkTrace.leftToJoin, b: longEdge,
                  t: [0, 0.25, 0.6, 0.8, 1],
                  colors: [[c(210, 50, 110), c(170, 20, 90), c(137, 2, 78),
                            c(150, 10, 80), c(180, 30, 95)],
                           [c(180, 30, 80), c(137, 2, 72), c(136, 2, 68),
                            c(130, 5, 66), c(150, 10, 70)],
                           [c(215, 62, 60), c(135, 14, 58), c(92, 5, 45),
                            c(125, 18, 55), c(165, 28, 55)],
                           [c(238, 100, 62), c(185, 42, 56), c(128, 24, 60),
                            c(136, 37, 63), c(175, 35, 55)],
                           [c(245, 120, 64), c(210, 62, 56), c(170, 40, 52),
                            c(215, 80, 60), c(245, 140, 80)]],
                  rimA: 1.2, rimB: 0, curve: 0.45, facing: 0.5,
                  // Under the curl the edge glows pink into red; along the
                  // stroke it is a hairline on the crimson rolled rim;
                  // round the U it glows broadly, yellow into orange.
                  glowA: { t in 10 - 7 * smooth((t - 0.10) / 0.12)
                                + 61 * smooth((t - 0.62) / 0.22)
                                + 30 * smooth((t - 0.86) / 0.10) },
                  glowB: { _ in 0 },
                  glowHueA: { t in 1 - smooth((t - 0.14) / 0.10) }),
            // The back sheet: coral down the stroke with magenta in its
            // fold, peach and white where it faces front at the base.
            // Its edges meet at the fold's tip, inside the U.
            Layer(a: sCurve, b: diagonal + foldRight.dropFirst(),
                  t: [0, 0.3, 0.55, 0.68, 0.8, 1],
                  colors: [[c(249, 71, 79), c(249, 71, 79), c(210, 45, 76),
                            c(160, 18, 68), c(132, 9, 63)],
                           [c(249, 71, 79), c(249, 71, 79), c(200, 35, 74),
                            c(132, 9, 63), c(150, 12, 65)],
                           [c(245, 80, 85), c(240, 70, 82), c(225, 50, 80),
                            c(215, 45, 75), c(240, 70, 70)],
                           [c(240, 90, 95), c(248, 130, 120), c(252, 175, 152),
                            c(253, 215, 190), c(254, 248, 230)],
                           [c(245, 120, 110), c(250, 150, 120), c(251, 160, 128),
                            c(251, 158, 126), c(252, 185, 150)],
                           [c(240, 120, 100), c(250, 150, 118), c(251, 158, 126),
                            c(252, 175, 140), c(252, 190, 150)]],
                  rimA: 1.0, rimB: 0.55, curve: 1.5, facing: 0.6,
                  // Beside the rolled rim the sheet starts pale yellow and
                  // grades to red; at the S-curve the edge is a hairline.
                  glowA: { t in 4 + 68 * smooth((t - 0.06) / 0.14)
                                - 64 * smooth((t - 0.40) / 0.16) },
                  glowB: { _ in 4 },
                  // Cream, peach, coral, then the sheet's red: no band.
                  glowHueA: { _ in 0.55 }),
            // The front sheet: the lip (orange-peach edge, coral middle,
            // cream highlight above its lower edge) and the stroke's right
            // side (deep magenta, orange-red along the diagonal).
            Layer(a: lipTop, b: front,
                  t: [0, 0.14, 0.28, 0.38, 0.47, 0.6, 1],
                  colors: [[c(252, 158, 84), c(252, 165, 100), c(252, 190, 140),
                            c(253, 220, 175), c(253, 235, 195)],
                           [c(253, 170, 100), c(252, 175, 120), c(253, 200, 155),
                            c(253, 225, 180), c(253, 245, 205)],
                           [c(253, 163, 93), c(252, 110, 95), c(252, 92, 93),
                            c(253, 215, 175), c(253, 248, 203)],
                           [c(252, 150, 110), c(250, 100, 100), c(245, 85, 95),
                            c(252, 205, 165), c(253, 245, 205)],
                           [c(252, 169, 170), c(250, 160, 162), c(245, 120, 130),
                            c(250, 90, 80), c(253, 110, 75)],
                           [c(208, 20, 82), c(160, 8, 65), c(125, 1, 57),
                            c(190, 25, 68), c(253, 85, 58)],
                           [c(215, 30, 80), c(170, 12, 66), c(135, 3, 58),
                            c(200, 35, 70), c(252, 110, 75)]],
                  rimA: 1.1, rimB: 0.5, curve: 0.55, facing: 0.55,
                  glowA: { t in 42 - 28 * smooth((t - 0.22) / 0.25)
                                - 8 * smooth((t - 0.47) / 0.08) },
                  glowB: { _ in 4 }),
        ]
    }

    /// The mark's outline, for asking whether a point lies on it (within
    /// 2 design px of a segment). Bucketed on a coarse grid, so the build
    /// stays cheap in an unoptimised app.
    struct Outline {
        let points: [SIMD2<Float>]
        private var cells: [Int: [Int]] = [:]
        private static let cell: Float = 16

        init(_ pts: [SIMD2<Float>]) {
            points = pts
            for i in pts.indices {
                let a = pts[i], b = pts[(i + 1) % pts.count]
                for k in Self.keys(near: (a + b) / 2, radius: simd_length(b - a) / 2 + 2) {
                    cells[k, default: []].append(i)
                }
            }
        }

        private static func keys(near p: SIMD2<Float>, radius r: Float) -> [Int] {
            let x0 = Int(((p.x - r) / cell).rounded(.down)), x1 = Int(((p.x + r) / cell).rounded(.down))
            let y0 = Int(((p.y - r) / cell).rounded(.down)), y1 = Int(((p.y + r) / cell).rounded(.down))
            var out = [Int]()
            for y in y0...y1 { for x in x0...x1 { out.append(y * 4096 + x) } }
            return out
        }

        func contains(_ p: SIMD2<Float>) -> Bool {
            let k = Int((p.y / Self.cell).rounded(.down)) * 4096 + Int((p.x / Self.cell).rounded(.down))
            for i in cells[k] ?? [] {
                let a = points[i], b = points[(i + 1) % points.count]
                let ab = b - a
                let t = min(max(simd_dot(p - a, ab) / max(simd_length_squared(ab), 1e-6), 0), 1)
                if simd_length(p - (a + ab * t)) < 2 { return true }
            }
            return false
        }
    }

    /// The backplate's colour: the ribbon's dark inner red (linear).
    static let backplate = SIMD3<Float>(pow(150 / 255, 2.2), pow(22 / 255, 2.2),
                                        pow(52 / 255, 2.2))

    /// Ear-clipping triangulation of a simple polygon (the silhouette).
    static func triangulate(_ poly: [SIMD2<Float>]) -> [Int] {
        var ids = Array(poly.indices)
        func cross(_ o: SIMD2<Float>, _ a: SIMD2<Float>, _ b: SIMD2<Float>) -> Float {
            (a.x - o.x) * (b.y - o.y) - (a.y - o.y) * (b.x - o.x)
        }
        // Orientation: the sign of the polygon's area.
        var area: Float = 0
        for i in poly.indices {
            let a = poly[i], b = poly[(i + 1) % poly.count]
            area += a.x * b.y - b.x * a.y
        }
        let sign: Float = area > 0 ? 1 : -1
        var out = [Int]()
        var guardCount = 0
        while ids.count > 3 && guardCount < 100_000 {
            guardCount += 1
            var clipped = false
            for k in ids.indices {
                let i0 = ids[(k + ids.count - 1) % ids.count], i1 = ids[k]
                let i2 = ids[(k + 1) % ids.count]
                let a = poly[i0], b = poly[i1], c = poly[i2]
                if cross(a, b, c) * sign <= 0 { continue }        // reflex
                var inside = false
                for j in ids where j != i0 && j != i1 && j != i2 {
                    let p = poly[j]
                    if cross(a, b, p) * sign >= 0 && cross(b, c, p) * sign >= 0
                        && cross(c, a, p) * sign >= 0 { inside = true; break }
                }
                if inside { continue }
                out += [i0, i1, i2]
                ids.remove(at: k)
                clipped = true
                break
            }
            if !clipped { break }      // degenerate: stop rather than loop
        }
        if ids.count == 3 { out += ids }
        return out
    }

    /// Smoothstep on 0...1.
    static func smooth(_ x: Float) -> Float {
        let c = min(max(x, 0), 1)
        return c * c * (3 - 2 * c)
    }

    // ---- tessellation ---------------------------------------------------------

    struct Vertex {
        var position: SIMD4<Float>   // x, y (design px), 0, 0
        var color: SIMD4<Float>      // linear rgb, 1
        var edge: SIMD4<Float>       // px to edge A, px to edge B, rim A, rim B
        var extra: SIMD4<Float>      // film, t, v, 0
        var sheen: SIMD4<Float>      // across direction xy, curve, facing
        var glow: SIMD4<Float>       // glow reach from edge A, from edge B
    }

    static let along = 480
    static let across = 16

    /// The mesh: vertex and index buffers, the index count, and how many
    /// of those indices (the first ones) are the silhouette backplate --
    /// drawn alone for the flat mark of the tiniest icon.
    static func build(device: MTLDevice) -> (MTLBuffer, MTLBuffer, Int, Int)? {
        var verts = [Vertex]()
        var idx = [UInt32]()
        // First, a backplate: the whole silhouette, filled in the dark
        // inner red, so that wherever two sheets meet no hairline crack
        // can show the background. Holes are cut from it like the strip.
        let outline = Outline(MarkTrace.silhouette)
        let plate = SIMD4<Float>(backplate, 1)
        for p in outline.points {
            verts.append(Vertex(position: [p.x, p.y, 0, 0], color: plate,
                                edge: [1e4, 1e4, 0, 0], extra: [1, 0, 0.5, 0],
                                sheen: [1, 0, 0, 0.5], glow: [0, 0, 0, 0]))
        }
        idx += triangulate(outline.points).map { UInt32($0) }
        let plateCount = idx.count
        for layer in layers {
            // Densest at the sheet's ends, where it meets other sheets.
            let ts = (0..<along).map { i -> Float in
                let u = Float(i) / Float(along - 1)
                return 0.35 * u + 0.65 * (0.5 - 0.5 * cos(.pi * u))
            }
            var a = resample(layer.a, at: ts)
            var b = resample(layer.b, at: ts)
            if layer.capEnd > 0 { taperEnd(&a, &b, ts: ts, fraction: layer.capEnd) }
            let base = UInt32(verts.count)
            for i in 0..<along {
                let t = ts[i]
                let chord = simd_length(b[i] - a[i])
                let dir = chord > 1e-3 ? (b[i] - a[i]) / chord
                    : simd_normalize(b[max(i - 1, 0)] - a[max(i - 1, 0)] + [1e-3, 0])
                // One rule for every edge: where it lies on the outline it
                // is the outline (a hairline and the warm outline glow, the
                // same weight everywhere); inside, a hairline at most.
                let rimA = outline.contains(a[i]) ? max(layer.rimA, 1.3)
                                                  : min(layer.rimA, 1.0)
                let rimB = outline.contains(b[i]) ? max(layer.rimB, 1.3)
                                                  : min(layer.rimB, 1.0)
                for j in 0..<across {
                    let v = Float(j) / Float(across - 1)
                    let p = a[i] + (b[i] - a[i]) * v
                    verts.append(Vertex(
                        position: [p.x, p.y, 0, 0],
                        color: SIMD4(color(layer, t, v), 1),
                        edge: [v * chord, (1 - v) * chord, rimA, rimB],
                        extra: [layer.film ? 1 : 0, t, v, 0],
                        sheen: [dir.x, dir.y, layer.curve, layer.facing],
                        glow: [layer.glowA(t), layer.glowB(t), layer.glowHueA(t), 0]))
                }
            }
            for i in 0..<(along - 1) {
                for j in 0..<(across - 1) {
                    let p = base + UInt32(i * across + j)
                    let q = p + UInt32(across)
                    idx += [p, q, p + 1, p + 1, q, q + 1]
                }
            }
        }
        guard let vb = device.makeBuffer(
                  bytes: verts, length: verts.count * MemoryLayout<Vertex>.stride),
              let ib = device.makeBuffer(
                  bytes: idx, length: idx.count * MemoryLayout<UInt32>.stride)
        else { return nil }
        return (vb, ib, idx.count, plateCount)
    }

    /// Bilinear in the layer's table (t rows, v at 0 / 0.5 / 1), sRGB in,
    /// linear out.
    static func color(_ l: Layer, _ t: Float, _ v: Float) -> SIMD3<Float> {
        var r = 0
        while r + 1 < l.t.count - 1 && t > l.t[r + 1] { r += 1 }
        let ft = min(max((t - l.t[r]) / max(l.t[r + 1] - l.t[r], 1e-4), 0), 1)
        func row(_ k: Int) -> SIMD3<Float> {
            let c = l.colors[k]
            let x = v * Float(c.count - 1)
            let j = min(Int(x), c.count - 2)
            return c[j] + (c[j + 1] - c[j]) * (x - Float(j))
        }
        let s = row(r) + (row(r + 1) - row(r)) * ft
        return SIMD3(pow(s.x / 255, 2.2), pow(s.y / 255, 2.2), pow(s.z / 255, 2.2))
    }

    /// Catmull-Rom through `pts`, then `n` points evenly spaced by arc
    /// length.
    static func resample(_ pts: [SIMD2<Float>], _ n: Int) -> [SIMD2<Float>] {
        resample(pts, at: (0..<n).map { Float($0) / Float(n - 1) })
    }

    /// Catmull-Rom through `pts`, then points at the given arc-length
    /// fractions (ascending, 0...1).
    static func resample(_ pts: [SIMD2<Float>], at fractions: [Float]) -> [SIMD2<Float>] {
        var dense = [SIMD2<Float>]()
        let k = pts.count
        for i in 0..<(k - 1) {
            let p0 = pts[max(i - 1, 0)], p1 = pts[i]
            let p2 = pts[i + 1], p3 = pts[min(i + 2, k - 1)]
            // Each term in steps, its scalars typed: integer literals
            // among SIMD2's operators sent an older Swift's type checker
            // past its time limit on this step.
            let two: Float = 2, three: Float = 3
            let four: Float = 4, five: Float = 5, half: Float = 0.5
            let a: SIMD2<Float> = two * p1
            let bPart: SIMD2<Float> = p2 - p0
            var cPart: SIMD2<Float> = two * p0 - five * p1
            cPart += four * p2 - p3
            var dPart: SIMD2<Float> = three * p1 - p0
            dPart += p3 - three * p2
            for s in 0..<32 {
                let f = Float(s) / 32
                let f2 = f * f
                let f3 = f2 * f
                var sum: SIMD2<Float> = a + bPart * f
                sum += cPart * f2
                sum += dPart * f3
                dense.append(sum * half)
            }
        }
        dense.append(pts[k - 1])
        var acc = [Float](repeating: 0, count: dense.count)
        for i in 1..<dense.count {
            acc[i] = acc[i - 1] + simd_length(dense[i] - dense[i - 1])
        }
        let total = acc.last ?? 1
        var out = [SIMD2<Float>]()
        var j = 0
        for f in fractions {
            let target = total * f
            while j + 1 < dense.count - 1 && acc[j + 1] < target { j += 1 }
            let seg = max(acc[j + 1] - acc[j], 1e-4)
            let f = min(max((target - acc[j]) / seg, 0), 1)
            out.append(dense[j] + (dense[j + 1] - dense[j]) * f)
        }
        return out
    }

    /// Taper a sheet's end to a point: over its last `fraction` of length
    /// the two edges close on the midline smoothly (no facets, no corner
    /// where they happened to converge).
    static func taperEnd(_ a: inout [SIMD2<Float>], _ b: inout [SIMD2<Float>],
                         ts: [Float], fraction: Float) {
        let t0 = 1 - fraction
        for i in a.indices where ts[i] > t0 {
            let s = (ts[i] - t0) / fraction
            let w = smooth(s) * 0.6 + s * s * 0.4          // reaches 1 at the tip
            let mid = (a[i] + b[i]) / 2
            a[i] = a[i] + (mid - a[i]) * w
            b[i] = b[i] + (mid - b[i]) * w
        }
    }

}
